### ISSUE TITLE
请问能否对DLNA做一下说明呢？谢谢

### ISSUE THREAD

**Issue by kukudemajia** [charleyzhu/HomeAssistant_Components#2]
- platform: dlna
有哪些属性要设置呢？
看到根目录下有一个dlna.py，media_player目录下又有一个dlna.py，不知所措了。。

**Comment by charleyzhu** [comment]
保持目录结构，复制两个dlna

**Comment by kukudemajia** [comment]
嗯嗯，非常感谢，已经运行成功并发现了，原来没有注意到目录结构，非常感谢
configuration.yaml只需填写
dlna:
就可以自动发现设备了，只是什么驱动还真不懂，继续学习，非常感谢您的分享

**Comment by kukudemajia** [comment]
出现以下错误，请问怎么解决呢？
2017-08-08 18:19:35 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.5fbeacdc86e246f7942d7c962294d468 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.homeassistant/custom_components/media_player/dlna.py", line 71, in update
    resp = self._device.GetTransportInfo()
  File "/root/.homeassistant/custom_components/media_player/dlna.py", line 304, in GetTransportInfo
    ["CurrentTransportState", "CurrentTransportStatus", "CurrentSpeed"])
  File "/root/.homeassistant/custom_components/media_player/dlna.py", line 423, in sendRequest
    respXml = etree.fromstring(respText)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1345, in XML
    return parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
