### ISSUE TITLE
貌似无法更新抓取到气象数据 log如下

### ISSUE THREAD

**Issue by iamsuperark** [charleyzhu/HomeAssistant_Components#6]
2017-08-30 05:01:59 WARNING (MainThread) [homeassistant.setup] Setup of sensor is taking over 10 seconds.
2017-08-30 05:01:59 WARNING (MainThread) [homeassistant.components.sensor] Setup of platform HeWeather is taking over 10 second
s.
2017-08-30 05:02:05 ERROR (Thread-5) [custom_components.sensor.HeWeather] Json Status Not Good!
2017-08-30 05:02:23 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor._temperature fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/WeatherChina.py", line 92, in update
    self._weatherData = json.loads(weatherDataStr)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
2017-08-30 05:03:02 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor._temperature is taking over 10 seconds
2017-08-30 05:03:10 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor._temperature fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/WeatherChina.py", line 92, in update
    self._weatherData = json.loads(weatherDataStr)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
2017-08-30 05:03:33 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor._temperature is taking over 10 seconds
2017-08-30 05:03:49 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor._temperature fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/WeatherChina.py", line 92, in update
    self._weatherData = json.loads(weatherDataStr)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
2017-08-30 05:04:04 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor._temperature is taking over 10 seconds
2017-08-30 05:04:05 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor._temperature fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/WeatherChina.py", line 92, in update
    self._weatherData = json.loads(weatherDataStr)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
2017-08-30 05:04:26 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor._temperature fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 225, in async_update_ha_state
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/WeatherChina.py", line 92, in update
    self._weatherData = json.loads(weatherDataStr)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by charleyzhu** [comment]
你在config中配置的城市代码是什么？

**Comment by iamsuperark** [comment]
根据这个列表https://cdn.heweather.com/china-city-list.txt


- platform: HeWeather
     api_key: 4e11fabf03be4bc5b42294466157404b
     interval: 300
     isShowWeatherPic: True
     city: pudongxinqu



________________________________
发件人: charleyzhu <notifications@github.com>
发送时间: 2017年8月30日 14:33
收件人: charleyzhu/HomeAssistant_Components
抄送: iamsuperark; Author
主题: Re: [charleyzhu/HomeAssistant_Components] 貌似无法更新抓取到气象数据 log如下 (#6)


你在config中配置的城市代码是什么？

―

**Comment by iamsuperark** [comment]
https://cdn.heweather.com/china-city-list.txt

- platform: HeWeather
     api_key: 4e11fabf03be4bc5b42294466157404b
     interval: 300
     isShowWeatherPic: True
     city: pudongxinqu

**Comment by charleyzhu** [comment]
你报错这个是WeatherChina(中国天气网)，不是和风天气

**Comment by iamsuperark** [comment]
sensor:
  - platform: WeatherChina
    CityCode:
      - 101020600009

用这个也试过

**Comment by iamsuperark** [comment]
现在不报错了，但是也没有显示出来

![image](https://user-images.githubusercontent.com/30721040/29860627-4143a160-8d99-11e7-8642-e9948167d98c.png)

**Comment by iamsuperark** [comment]
- platform: HeWeather
     api_key: 4e11fabf03be4bc5b42294466157404b
     interval: 300
     isShowWeatherPic: True
     city: pudongxinqu
     monitored_conditions:

对应这个的报错是
2017-08-30 07:39:54 ERROR (MainThread) [homeassistant.bootstrap] Error loading /home/homeassistant/.homeassistant/configuration
.yaml: mapping values are not allowed here
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 105, column 13

**Comment by charleyzhu** [comment]
你这yaml格式不规范

**Comment by iamsuperark** [comment]
显示的问题吧，我用的是-,在这边回帖就显示成点了，是不是缩进有问题

**Comment by iamsuperark** [comment]
把和风的去掉了，只留下WeatherChina,

![image](https://user-images.githubusercontent.com/30721040/29861780-01a80c18-8d9d-11e7-8389-aea4bfdce610.png)

仍然无法显示

![image](https://user-images.githubusercontent.com/30721040/29861789-0f16f7f6-8d9d-11e7-8a39-7439f85378a2.png)

**Comment by iamsuperark** [comment]
呃，7月份之后改api接口了，我把hewhether.py里面的改了This plugin invokes the API https://free-api.heweather.com/v5/weather?city=yourcity&key=yourkey for Chinese cities only. 还是不行。。。。

**Comment by iamsuperark** [comment]
最后把城市代码改成CN101020600可以了。。。。。。
